### ISSUE TITLE
Why does it require imagemagick...

### ISSUE THREAD

**Issue by gjedeer** [Jolg42/ovh-export-dns#1]
I'm trying to run your project on ubuntu 14.04 x86_64. I've ran `bundle` per your instructions, then:

```
➜  ovh-export-dns git:(master) ✗ ruby app.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- FileUtils (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from app.rb:3:in `<main>'
```

Okay, I guess that some module named FileUtils is needed:

```
➜  ovh-export-dns git:(master) ✗ sudo gem install fileutils
Fetching: rmagick-2.15.4.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing fileutils:
        ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
checking for gcc... yes
checking for Magick-config... no
checking for pkg-config... yes
Package MagickCore was not found in the pkg-config search path.
Perhaps you should add the directory containing `MagickCore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'MagickCore' found
checking for outdated ImageMagick version (<= 6.4.9)... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/ruby1.9.1


Gem files will remain installed in /var/lib/gems/1.9.1/gems/rmagick-2.15.4 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/rmagick-2.15.4/ext/RMagick/gem_make.out
```

Hmm... 

I guess I could follow this road and install the whole rmagick dev environment but maybe you could avoid this (rather unnecessary) dependence with some simple change to the code?

**Comment by gjedeer** [comment]
Actually, never mind, it was faster to rewrite it with python :)

**Comment by Jolg42** [comment]
@gjedeer Haha ! It looks like the FileUtils gem require rmagick, too many dependencies for a little script sometimes :bomb: 
And yes this was a simple script so you can easily rewrite it! By the way can you show me your python script?

**Comment by gjedeer** [comment]
Hi, sure! https://gist.github.com/gjedeer/4e3837ebb17b5d7db4ce

Requires:

```
pip install ovh
```

first
